### ISSUE TITLE
add topic tag `density-functional-theory`

### ISSUE THREAD

**Issue by Beliavsky** [f-fathurrahman/ffr-PWDFT#1]
I suggest adding the topic `density-functional-theory` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by f-fathurrahman** [comment]
Hi @Beliavsky , thank you for the issue. The plane wave code is somewhat not updated as I have put my effort to PWDFT.jl. But, someday I intend to implement the nonlocal pseudopotential stuffs.
